apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-command-service
  namespace: bookstore-ns
  labels:
    app: book-command-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-command-service
  template:
    metadata:
      labels:
        app: book-command-service
    spec:
      containers:
        - name: book-command-service
          image: 780159647368.dkr.ecr.us-east-1.amazonaws.com/bookstore/book-command-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: DATABASE_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: MYSQL_DATABASE
              value: books_db
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: gemini-api-key
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
