FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY sql/ ./sql/

EXPOSE 3000

CMD ["python", "-m", "flask", "--app", "app/main.py", "run", "--host=0.0.0.0", "--port=3000"]
