apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
  labels:
    app: crm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
        - name: crm-service
          image: 780159647368.dkr.ecr.us-east-1.amazonaws.com/bookstore/crm-service:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: "98.88.99.206:9092,34.195.107.7:9092,54.221.160.63:9092"
            - name: KAFKA_TOPIC
              value: vdodia.customer.evt
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: smtp-user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: smtp-password
            - name: ANDREW_ID
              value: vdodia
